<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" ignored="0" total="12" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="224" started-at="2018-11-13T04:22:39Z" finished-at="2018-11-13T04:22:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="224" started-at="2018-11-13T04:22:39Z" finished-at="2018-11-13T04:22:39Z">
      <class name="com.scp.test.ATest">
        <test-method status="PASS" signature="m1()[pri:0, instance:com.scp.test.ATest@8b96fde]" name="m1" duration-ms="14" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="PASS" signature="m2()[pri:0, instance:com.scp.test.ATest@8b96fde]" name="m2" duration-ms="2" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="PASS" signature="m3()[pri:0, instance:com.scp.test.ATest@8b96fde]" name="m3" duration-ms="1" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m4()[pri:0, instance:com.scp.test.ATest@8b96fde]" name="m4" duration-ms="1" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m4 -->
        <test-method status="PASS" signature="m5()[pri:0, instance:com.scp.test.ATest@8b96fde]" name="m5" duration-ms="2" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m5 -->
      </class> <!-- com.scp.test.ATest -->
      <class name="com.scp.test.BTest">
        <test-method status="FAIL" signature="p3()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p3" duration-ms="4" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[mark this as a fail test case]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: mark this as a fail test caseat org.testng.Assert.fail(Assert.java:96)at com.scp.test.BTest.p3(BTest.java:23)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p3 -->
        <test-method status="FAIL" signature="p4()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p4" duration-ms="1" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[mark this as a fail test case]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: mark this as a fail test caseat org.testng.Assert.fail(Assert.java:96)at com.scp.test.BTest.p4(BTest.java:29)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p4 -->
        <test-method status="PASS" signature="p5()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p5" duration-ms="11" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p5 -->
        <test-method status="PASS" signature="p6()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p6" duration-ms="1" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p6 -->
        <test-method status="PASS" signature="p7()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p7" duration-ms="1" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p7 -->
        <test-method status="PASS" signature="p1()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p1" duration-ms="1" started-at="2018-11-13T09:52:39Z" finished-at="2018-11-13T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p1 -->
        <test-method status="SKIP" signature="p2()[pri:0, instance:com.scp.test.BTest@2ea6137]" name="p2" duration-ms="0" started-at="2018-11-13T09:52:39Z" depends-on-methods="com.scp.test.BTest.p3" finished-at="2018-11-13T09:52:39Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method BTest.p2()[pri:0, instance:com.scp.test.BTest@2ea6137] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method BTest.p2()[pri:0, instance:com.scp.test.BTest@2ea6137] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- p2 -->
      </class> <!-- com.scp.test.BTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
